CREATE PROC FI_SP_VerificaCliente
	@CPF VARCHAR (14),
	@Id  BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT 1 FROM CLIENTES WITH(NOLOCK) WHERE CPF = @CPF
	ELSE
		SELECT 1 FROM CLIENTES WITH(NOLOCK) WHERE CPF = @CPF AND ID <> @Id
END